### ISSUE TITLE
Haramfu error BadZipFile: File is not a zip file

### ISSUE THREAD

**Issue by benagastov** [Linaqruf/Super-Stable-Diffusion-Web-UI#2]
Hello, I usually run the haramfu model in colab notebook. Why now I always get error from colab when I run it again?
Apologize if I ask a question here, but HF doesn't have DM at this moment. I am impressed how different img2img result if I use Ranma diffusion and AcertainModel which can alter realistic photos to anime pictures better and full of details.

**Comment by Linaqruf** [comment]
I apologize for the late reply. You need to use the latest version of the haramfu notebook in this repository, as I have updated my HF token.

**Comment by benagastov** [comment]
I am sorry but it seems like your huggingface repo for Haramfu is removed already
![image](https://user-images.githubusercontent.com/106045877/210141049-a86eab6e-2481-4a3b-bdda-01afc318a3a6.png)

**Comment by benagastov** [comment]
Thank you very much! I think it works great now
